# Codecov Configuration for ggen-spec-kit
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "50...90"  # Start at 50%, target 90%

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 50%
        informational: false
    changes:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "**/__pycache__"
  - "**/.pytest_cache"
  - "**/reports/"
  - "setup.py"
  - "**/__init__.py"
