"""
Generated by ggen from cli-commands.ttl
Constitutional equation: commands/*.py = μ(cli-commands.ttl)
DO NOT EDIT THIS FILE MANUALLY - regenerate with: ggen sync
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import typer
from rich.console import Console

if TYPE_CHECKING:
    from pathlib import Path

console = Console()


# ============================================================================
# CheckCommand
# ============================================================================

check_app = typer.Typer(
    name="check",
    help="""Check for required and optional tools""",
)


@check_app.callback(invoke_without_command=True)
def check_cmd(
    check_include_optional: bool = typer.Option(
        True,
        "--include-optional",
        help="""Include optional tools in the check""",
    ),
    check_json: bool = typer.Option(
        False,
        "--json",
        help="""Output results as JSON""",
    ),
    check_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Show detailed information about each tool""",
    ),
) -> None:
    """Check for required and optional tools"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]CheckCommand executed[/dim]")


# ============================================================================
# GgenCommand
# ============================================================================

ggen_app = typer.Typer(
    name="ggen",
    help="""RDF-first code generation command group""",
)


@ggen_app.callback(invoke_without_command=True)
def ggen_cmd() -> None:
    """RDF-first code generation command group"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]GgenCommand executed[/dim]")


# ============================================================================
# GgenSyncCommand
# ============================================================================

ggensync_app = typer.Typer(
    name="ggensync",
    help="""Transform RDF specifications to code/markdown using ggen sync""",
)


@ggensync_app.callback(invoke_without_command=True)
def ggensync_cmd(
    ggen_sync_dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="""Preview changes without writing files""",
    ),
    ggen_sync_json: bool = typer.Option(
        False,
        "--json",
        help="""Output results as JSON""",
    ),
    ggen_sync_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Enable verbose output""",
    ),
    ggen_sync_watch: bool = typer.Option(
        False,
        "--watch",
        "-w",
        help="""Watch for file changes and automatically re-run""",
    ),
) -> None:
    """Transform RDF specifications to code/markdown using ggen sync"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]GgenSyncCommand executed[/dim]")


# ============================================================================
# InitCommand
# ============================================================================

init_app = typer.Typer(
    name="init",
    help="""Initialize a new Specify project from the latest template""",
)


@init_app.callback(invoke_without_command=True)
def init_cmd(
    init_project_name: str | None = typer.Argument(
        None,
        help="""Name of the project to create. Omit if using --here.""",
    ),
    init_ai: str | None = typer.Option(
        None,
        "--ai",
        "-a",
        help="""AI assistant type (claude, cursor, copilot)""",
    ),
    init_debug: bool = typer.Option(
        False,
        "--debug",
        help="""Enable debug output""",
    ),
    init_github_token: str | None = typer.Option(
        None,
        "--github-token",
        help="""GitHub token for authenticated requests""",
    ),
    init_here: bool = typer.Option(
        False,
        "--here",
        "-H",
        help="""Initialize in current directory instead of creating new""",
    ),
    init_no_git: bool = typer.Option(
        False,
        "--no-git",
        help="""Skip git repository initialization""",
    ),
    init_script: str | None = typer.Option(
        None,
        "--script",
        "-s",
        help="""Script type for helper scripts (sh or ps1)""",
    ),
    init_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Enable verbose output""",
    ),
) -> None:
    """Initialize a new Specify project from the latest template"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]InitCommand executed[/dim]")


# ============================================================================
# PmCommand
# ============================================================================

pm_app = typer.Typer(
    name="pm",
    help="""Process mining command group using pm4py""",
)


@pm_app.callback(invoke_without_command=True)
def pm_cmd() -> None:
    """Process mining command group using pm4py"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]PmCommand executed[/dim]")


# ============================================================================
# PmConformCommand
# ============================================================================

pmconform_app = typer.Typer(
    name="pmconform",
    help="""Check conformance between event log and process model""",
)


@pmconform_app.callback(invoke_without_command=True)
def pmconform_cmd(
    pm_conform_log_file: Path = typer.Argument(
        ...,
        help="""Input event log file (CSV or XES)""",
    ),
    pm_conform_model_file: Path = typer.Argument(
        ...,
        help="""Process model file (PNML or BPMN)""",
    ),
    pm_conform_json: bool = typer.Option(
        False,
        "--json",
        help="""Output results as JSON""",
    ),
    pm_conform_method: str | None = typer.Option(
        None,
        "--method",
        "-m",
        help="""Conformance method: token or alignment""",
    ),
    pm_conform_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Show detailed diagnostics""",
    ),
) -> None:
    """Check conformance between event log and process model"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]PmConformCommand executed[/dim]")


# ============================================================================
# PmDiscoverCommand
# ============================================================================

pmdiscover_app = typer.Typer(
    name="pmdiscover",
    help="""Discover a process model from an event log""",
)


@pmdiscover_app.callback(invoke_without_command=True)
def pmdiscover_cmd(
    pm_discover_input_file: Path = typer.Argument(
        ...,
        help="""Input event log file (CSV or XES)""",
    ),
    pm_discover_activity: str | None = typer.Option(
        None,
        "--activity",
        help="""Column name for activity (CSV only)""",
    ),
    pm_discover_algorithm: str | None = typer.Option(
        None,
        "--algorithm",
        "-a",
        help="""Discovery algorithm: alpha, heuristic, inductive, ilp""",
    ),
    pm_discover_case_id: str | None = typer.Option(
        None,
        "--case-id",
        help="""Column name for case ID (CSV only)""",
    ),
    pm_discover_json: bool = typer.Option(
        False,
        "--json",
        help="""Output results as JSON""",
    ),
    pm_discover_noise: float = typer.Option(
        None,
        "--noise",
        "-n",
        help="""Noise threshold for inductive miner (0.0-1.0)""",
    ),
    pm_discover_output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="""Output file for discovered model""",
    ),
    pm_discover_timestamp: str | None = typer.Option(
        None,
        "--timestamp",
        help="""Column name for timestamp (CSV only)""",
    ),
    pm_discover_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Show detailed progress""",
    ),
) -> None:
    """Discover a process model from an event log"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]PmDiscoverCommand executed[/dim]")


# ============================================================================
# PmStatsCommand
# ============================================================================

pmstats_app = typer.Typer(
    name="pmstats",
    help="""Extract statistics from an event log""",
)


@pmstats_app.callback(invoke_without_command=True)
def pmstats_cmd(
    pm_stats_input_file: Path = typer.Argument(
        ...,
        help="""Input event log file (CSV or XES)""",
    ),
    pm_stats_case_id: str | None = typer.Option(
        None,
        "--case-id",
        help="""Column name for case ID""",
    ),
    pm_stats_json: bool = typer.Option(
        False,
        "--json",
        help="""Output results as JSON""",
    ),
    pm_stats_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Show detailed statistics""",
    ),
) -> None:
    """Extract statistics from an event log"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]PmStatsCommand executed[/dim]")


# ============================================================================
# SpiffCommand
# ============================================================================

spiff_app = typer.Typer(
    name="spiff",
    help="""BPMN workflow command group using SpiffWorkflow""",
)


@spiff_app.callback(invoke_without_command=True)
def spiff_cmd() -> None:
    """BPMN workflow command group using SpiffWorkflow"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]SpiffCommand executed[/dim]")


# ============================================================================
# SpiffRunWorkflowCommand
# ============================================================================

spiffrunworkflow_app = typer.Typer(
    name="spiffrunworkflow",
    help="""Execute a BPMN workflow file""",
)


@spiffrunworkflow_app.callback(invoke_without_command=True)
def spiffrunworkflow_cmd(
    spiff_run_workflow_file: Path = typer.Argument(
        ...,
        help="""BPMN workflow file to execute""",
    ),
    spiff_run_export_json: Path | None = typer.Option(
        None,
        "--export-json",
        help="""Export results to JSON""",
    ),
) -> None:
    """Execute a BPMN workflow file"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]SpiffRunWorkflowCommand executed[/dim]")


# ============================================================================
# SpiffValidateCommand
# ============================================================================

spiffvalidate_app = typer.Typer(
    name="spiffvalidate",
    help="""Execute full OTEL validation workflow""",
)


@spiffvalidate_app.callback(invoke_without_command=True)
def spiffvalidate_cmd(
    spiff_validate_export_json: Path | None = typer.Option(
        None,
        "--export-json",
        help="""Export results to JSON file""",
    ),
    spiff_validate_iterations: int = typer.Option(
        None,
        "--iterations",
        "-i",
        help="""Number of validation iterations""",
    ),
    spiff_validate_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Verbose output""",
    ),
) -> None:
    """Execute full OTEL validation workflow"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]SpiffValidateCommand executed[/dim]")


# ============================================================================
# VersionCommand
# ============================================================================

version_app = typer.Typer(
    name="version",
    help="""Show version information""",
)


@version_app.callback(invoke_without_command=True)
def version_cmd(
    version_check_updates: bool = typer.Option(
        False,
        "--check-updates",
        "-u",
        help="""Check for available updates""",
    ),
    version_json: bool = typer.Option(
        False,
        "--json",
        help="""Output results as JSON""",
    ),
    version_verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="""Show detailed build information""",
    ),
) -> None:
    """Show version information"""
    # Delegate to ops layer (three-tier architecture)
    console.print("[dim]VersionCommand executed[/dim]")


# ============================================================================
# Main Application Assembly
# ============================================================================

app = typer.Typer(
    name="specify",
    help="Specify CLI - RDF-first spec-driven development toolkit",
)

# Register command groups


app.add_typer(ggen_app, name="ggen")


app.add_typer(pm_app, name="pm")


app.add_typer(spiff_app, name="wf")


# Register root commands


app.add_typer(check_app, name="check")


app.add_typer(init_app, name="init")


app.add_typer(version_app, name="version")


def main() -> None:
    """Entry point."""
    app()


if __name__ == "__main__":
    main()
