# Type stubs for sklearn.decomposition
from typing import Any
from numpy.typing import NDArray

class PCA:
    def __init__(self, n_components: int | None = None, **kwargs: Any) -> None: ...
    def fit(self, X: NDArray[Any], y: Any = None) -> PCA: ...
    def transform(self, X: NDArray[Any]) -> NDArray[Any]: ...
    def fit_transform(self, X: NDArray[Any], y: Any = None) -> NDArray[Any]: ...
