# Type stubs for sklearn.ensemble
from typing import Any
from numpy.typing import NDArray

class RandomForestClassifier:
    def __init__(self, **kwargs: Any) -> None: ...
    def fit(self, X: NDArray[Any], y: NDArray[Any]) -> RandomForestClassifier: ...
    def predict(self, X: NDArray[Any]) -> NDArray[Any]: ...
    def predict_proba(self, X: NDArray[Any]) -> NDArray[Any]: ...
