# Type stubs for sklearn.manifold
from typing import Any
from numpy.typing import NDArray

class TSNE:
    def __init__(self, n_components: int = 2, **kwargs: Any) -> None: ...
    def fit(self, X: NDArray[Any], y: Any = None) -> TSNE: ...
    def fit_transform(self, X: NDArray[Any], y: Any = None) -> NDArray[Any]: ...
