# Type stubs for sklearn.preprocessing
from typing import Any
from numpy.typing import NDArray

class StandardScaler:
    def __init__(self, **kwargs: Any) -> None: ...
    def fit(self, X: NDArray[Any], y: Any = None) -> StandardScaler: ...
    def transform(self, X: NDArray[Any]) -> NDArray[Any]: ...
    def fit_transform(self, X: NDArray[Any], y: Any = None) -> NDArray[Any]: ...
